#Estatisticas

In [ ]:
# Variaveis são as caracteristicas que queremos observar ou medir nos elementos de uma população ou  (caracteristicas)
#Dados: São os valores concretos observados/ medidos para cada variável, em cada elemento.
#Variavel qualitativa : Variavel de adjetivo (qualidade). Não dá pra somar
#Nominal: Categoria sem ordem. EX: cor dos olhos
#Ordinal: Categorias com ordem, que dá pra ordenar. Ex gra de instrução.

#Variavel quantitativa: Trata-se de algum valor numérico.
#discreta: numeros contáveis, geralmente são números inteiros.
#contínua: valores numéricos em uma escala contínua dentro de um intervalo.

times = ["Corinthians", "São Paulo", "Santos"]
# Qualitativa - nominal

numero_filhos = [0,1,1,2,3]
# Quantitativa - discreta

satisfacao = ["péssimo", "ruim", "ótimo","bom"]
# Quaitativa - ordinal

alturas = [1.65, 1.72, 2.02, 1.68]
#quantitativa - contínua

#Média

In [ ]:
# Soma de valores divididos pela mesma quantidade de números
alturas = [1.65, 1.72, 2.02, 1.68]

media = (1.65+1.72+2.02+1.68) / 4
print(media)

#acumulador
soma = 0
for i in alturas:
  soma = soma + i

medias = soma/len(alturas)
print(medias)

#sum (Função de soma)

soma1 = sum(alturas)
media2 = soma1/len(alturas)
print(media2)

1.7675
1.7675
1.7675

#Mediana

In [ ]:
#Informação que está no meio de uma lista ordenada

numero_filhos = [0,1,1,2,2,3]

#ordenar

numero_filhos.sort() #sort ordena os dados
tamanho = len(numero_filhos)
meio = 0
mediana = 0
if tamanho % 2 == 1:
  meio = (tamanho / 2 -0.5)-1
  mediana = numero_filhos[int(meio)]

else:
  mediana = (numero_filhos[int(tamanho / 2)] + numero_filhos[int(tamanho / 2 -1)])/2

print(mediana)

1.5

#MODA

In [ ]:
#Busca a informação que mais se repete

satisfacao = ["péssimo", "ruim", "ruim","ótimo","bom" , "bom" ,"bom"]

dicionario_satisfacao = {}

for satis in satisfacao: # Roda variável satis na lista
  if satis in dicionario_satisfacao.keys(): #Compara a variavel satis com o dicionário
    dicionario_satisfacao[satis] += 1 # Acrescenta 1 de valor se a chave for existente
  else:
    dicionario_satisfacao[satis] = 1 # Cria a chave e adiciona 1 no valor

print(dicionario_satisfacao)

moda = ""
maior = 0
for c,v in dicionario_satisfacao.items():
  if v > maior: # Verifica o valor se o valor for maior no dicionário.
    maior = v
    moda = c

print(f"A moda é {moda} e repetiu {maior} vezes")

{'péssimo': 1, 'ruim': 2, 'ótimo': 1, 'bom': 3}
A moda é bom e repetiu 3 vezes

#Funções prontas

In [ ]:
# sum - faz soma
sum(alturas)

# max - Pega o valor maior
max(alturas)

# min - Pega o menor valor
min(alturas)

# len - retorna a quantidade de elementos na lista
len(alturas)

4

#Biblioteca

In [ ]:
# imporar biblioteca

import statistics  #comando pra importar a biblioteca

statistics.mean(alturas) #Média
statistics.median(alturas) #Mediana
statistics.mode(satisfacao) #Moda

'bom'

#Biblioteca Pandas

In [37]:
#Ferramenta para trabalhar com ciência de dados

#import (nome biblioteca) as (apelido) - Comando pra chamar a biblioteca

import pandas as pd

#Series  = Lista
#Dataframes = Dicionário

#ler dado

In [39]:
#Importar dados
df = pd.read_csv("base_vendas.csv")
# DF = Data frame
#pd - apelido da biblioteca
#.read - pra ler
#_csv - formato

#Exibir dados

In [45]:
# Pra exibir as primeiras linhas
df.head(10) # Número mostra a quantidade de linhas pra exibir

# Pra exibir as ultimas linhas
df.tail(10)

#Pra ver só as colunas  - Sem parenteses pq não é uma função
df.columns

#Mostrar as informações da tabela.
#df.info()

Index(['matricula_funcionario', 'Nome Funcionario', 'Cargo', 'codigo_loja',
       'nome_loja', 'codigo_produto', 'descricao_produto', 'Categoria',
       'preco_custo', 'valor_unitario', 'quantidade', 'comissao', 'dt_venda',
       'dt_entrega'],
      dtype='object')

#Organizar colunas

In [52]:
# Reorganizando o nome das colunas para a programação
df.columns = ['matricula_funcionario', 'nome_funcionario', 'cargo', 'codigo_loja',
       'nome_loja', 'codigo_produto', 'descricao_produto', 'categoria',
       'preco_custo', 'valor_unitario', 'quantidade', 'comissao', 'data_venda',
       'data_entrega']
df.columns

Index(['matricula_funcionario', 'nome_funcionario', 'cargo', 'codigo_loja',
       'nome_loja', 'codigo_produto', 'descricao_produto', 'categoria',
       'preco_custo', 'valor_unitario', 'quantidade', 'comissao', 'data_venda',
       'data_entrega'],
      dtype='object')

#Organizar arquivos json

In [53]:
dj = pd.read_json("base_vendas.json")

dj.columns

Index(['matricula_funcionario', 'Nome Funcionario', 'Cargo', 'codigo_loja',
       'nome_loja', 'codigo_produto', 'descricao_produto', 'Categoria',
       'preco_custo', 'valor_unitario', 'quantidade', 'comissao', 'dt_venda',
       'dt_entrega'],
      dtype='object')

In [58]:
dj.columns = ['matricula_funcionario', 'nome_funcionario', 'cargo', 'codigo_loja',
       'nome_loja', 'codigo_produto', 'descricao_produto', 'categoria',
       'preco_custo', 'valor_unitario', 'quantidade', 'comissao', 'data_venda',
       'data_entrega']

dj.columns

Index(['matricula_funcionario', 'nome_funcionario', 'cargo', 'codigo_loja',
       'nome_loja', 'codigo_produto', 'descricao_produto', 'categoria',
       'preco_custo', 'valor_unitario', 'quantidade', 'comissao', 'data_venda',
       'data_entrega'],
      dtype='object')

#Escrever com pandas

In [57]:
dj.to_json("dados_organizados.json")
# Atualiza o arquivo, se ele não existir, cria um novo.

#CSV com ponto e virgula

In [ ]:
# Comando SEP serve para indicar o separador do data frame, por padrão é virgula, mas assim podems indicar o ponto e vírgula
df2 = pd.read_csv("base_vendas_ponto_virgula.csv", sep= ";")
df2.head()

#Ler arquivos HTML

In [71]:
# HTML necessário criar uma lista, por isso o [0] indicando o inicio
dh = pd.read_html("base_vendas.html")[0]

dh.head(5)

,matricula_funcionario,Nome Funcionario,Cargo,codigo_loja,nome_loja,codigo_produto,descricao_produto,Categoria,preco_custo,valor_unitario,quantidade,comissao,dt_venda,dt_entrega
0,123456111,José Maria,Vendedor,CL001,Loja Matriz,10013,Fogão,Eletrodomésticos,2109,4041,1,NaN,28/09/2020 16:19,05/10/2020 16:31
1,123456111,José Maria,Vendedor,CL001,Loja Matriz,10018,Colchão,Casa,1099,2499,1,NaN,07/03/2020 12:47,08/03/2020 12:47
2,123456111,José Maria,Vendedor,CL001,Loja Matriz,10014,Geladeira,Eletrodomésticos,6999,13469,1,NaN,21/04/2019 10:48,23/04/2019 15:55
3,123456111,José Maria,Vendedor,CL001,Loja Matriz,10001,Smartphone,Eletrônicos,8999,16769,1,NaN,07/05/2020 17:59,08/05/2020 14:31
4,123456111,José Maria,Vendedor,CL001,Loja Matriz,10004,Máquina Lavar Roupa,Eletrodomésticos,1099,17091,1,5.0,14/08/2019 16:56,19/08/2019 15:52

#Ler arquivos TSV

In [77]:
# Separação \t indica o espaço de um TAB
dt = pd.read_csv("base_vendas_tab.tsv", sep="\t")
dt.head(5)

,matricula_funcionario,Nome Funcionario,Cargo,codigo_loja,nome_loja,codigo_produto,descricao_produto,Categoria,preco_custo,valor_unitario,quantidade,comissao,dt_venda,dt_entrega
0,123456111,José Maria,Vendedor,CL001,Loja Matriz,10013,Fogão,Eletrodomésticos,"210,9","404,1",1,NaN,28/09/2020 16:19,05/10/2020 16:31
1,123456111,José Maria,Vendedor,CL001,Loja Matriz,10018,Colchão,Casa,"109,9","249,9",1,NaN,07/03/2020 12:47,08/03/2020 12:47
2,123456111,José Maria,Vendedor,CL001,Loja Matriz,10014,Geladeira,Eletrodomésticos,"699,9","1346,9",1,NaN,21/04/2019 10:48,23/04/2019 15:55
3,123456111,José Maria,Vendedor,CL001,Loja Matriz,10001,Smartphone,Eletrônicos,"899,9","1676,9",1,NaN,07/05/2020 17:59,08/05/2020 14:31
4,123456111,José Maria,Vendedor,CL001,Loja Matriz,10004,Máquina Lavar Roupa,Eletrodomésticos,1099,"1709,1",1,"0,05",14/08/2019 16:56,19/08/2019 15:52